# Generated by Django 5.2.6 on 2025-09-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Package Categories'},
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
